### ISSUE TITLE
Bug: Hide CDN Tab css is output on all page loads, breaking ajax requests

### ISSUE THREAD

**Issue by thejamescollins** [pressable/pressable-cache-management#12]
We have a website running Toolset Types and Views plugins, which does ajax-based filtering of information.

After enabling the Pressable Cache Management plugin, these AJAX requests are broken due to the AJAX responses including some CSS:

<img width="2438" alt="Screenshot 2024-10-01 at 1 34 00 PM" src="https://github.com/user-attachments/assets/c50d1fb8-4c01-464e-90bc-6b7f92ae12d7">

This bug likely affects any other ajax responses in WordPress, including Gravity Forms form submissions or possibly even WordPress core built in ajax requests.

Looks like the code is here: https://github.com/pressable/pressable-cache-management/blob/c77397d2ca99ebe27648b379f1b3c83853ac8766/admin/settings-page.php#L154, with the bug being introduced in 7b16e69469063a6855d46824c86e29467b9304dc (version 4.2.8 released this 23 July 2024).

Could the cache management plugin be fixed so that it does not output HTML/CSS in other Ajax JSON responses?

Thank you

**Comment by otarhe** [comment]
Thanks @thejamescollins i've merged the changes on the main plugin branch. The new version of the plugin should reflect the new changes please upgrade to version 4.4.9  [here.](https://github.com/pressable/pressable-cache-management/releases/download/4.4.9/pressable-cache-management.zip)

**Comment by thejamescollins** [comment]
Thanks @otarhe, v4.4.9 indeed works as expected.
James
