### ISSUE TITLE
Look at utilizing WordPress's WP_HTTP library over using Curl?

### ISSUE THREAD

**Issue by georgestephanis** [pressable/pressable-cache-management#4]
https://github.com/pressable/pressable-cache-management-plugin/blob/a215f7c5fbd864fccea0b52ebfc1b703cdf5a215/admin/custom-functions/api_connection.php#L14-L26

Could likely be converted to

https://developer.wordpress.org/reference/classes/wp_http/

**Comment by otarhe** [comment]
I have updated  the curl method for the API connection in favor of WP_HTTP.
